sudo: required
services:
  - docker

before_install:
  - docker build -t juvegitau/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run juvegitau/react-test npm test -- --coverage

after_success:
  - docker build -t juvegitau/multi-client ./client
  - docker build -t juvegitau/multi-nginx ./nginx
  - docker build -t juvegitau/multi-server ./server
  - docker build -t juvegitau/multi-worker ./worker
  #Login to docker CLI
  #- echo "$DOCKER_PASSWORD"
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  #- docker login -u juvegitau --password
  # push to docker hub
  - docker push juvegitau/multi-client
  - docker push juvegitau/multi-nginx
  - docker push juvegitau/multi-server
  - docker push juvegitau/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-509179872997"
    bucket_path: "docker-multi"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"

